#!/usr/bin/env sh
#
# wm independent hotkeys
#

# terminal emulator
super + Return
	alacritty

# program launcher
super + @space
        rofi -no-lazy-grab -show drun -modi drun -theme ~/.config/rofi/silver.rasi

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# quit/restart bspwm
super + shift + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

# swap the current node and the biggest window
super + g
	bspc node -s biggest.window

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# move/resize
#

# expand a window by moving one of its side outward
super + ctrl + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + ctrl + shift + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# fn keys
XF86MonBrightness{Up,Down}
        ~/.config/sxhkd/scripts/brightness.sh {-inc 2,-dec 2}

# volume keys
XF86Audio{RaiseVolume,LowerVolume,Mute}
	~/.config/sxhkd/scripts/volume.sh {-i 5,-d 5,-t}

# screenshot
super + Print
      scrot '%Y-%m-%d-%s_$wx$h_scrot.png' -e 'mv $f ~/Pictures/Screenshots'
